# === PREFIXLOAD TOOL CONFIGURATION ===
# The endpoint URL of your S3-compatible storage
endpoint: "https://s3.example.com"

# The name of your S3 bucket to upload files to
bucket: "name_bucket"

# The AWS region. Required by the SDK, even for non-AWS services.
# For many S3-compatible stores (like MinIO), you can leave this as "us-east-1".
region: "us-east-1"

# Set to `true` for S3-compatible services that require path-style addressing
# (e.g., MinIO). If you are using AWS S3, this should be `false`.
# - Path-style:    https://s3.example.com/my-bucket/
# - Virtual-hosted:  https://my-bucket.s3.example.com/
force_path_style: false

# The upload part size in bytes (for multipart upload; 15728640 = 15MB)
part_size: 15728640

# Path to the local directory where your backups are stored
local_directory_path: "/path/to/file"

# Mapping rules for uploading specific files to specific cloud subdirectories
directory_struct:
  # Each entry defines a file prefix and the corresponding cloud directory in the bucket.
  # Example: A file named "prefix_1_backup_somefile.sql" will be uploaded to "name_backet/prefix_1/prefix_1_backup_somefile.sql"

  - local_name_prefix: "prefix_1_backup" # Local files starting with this prefix
    remote_path: "prefix_1" # Will be uploaded into this directory inside the bucket

  - local_name_prefix: "prefix_2_backup"
    remote_path: "prefix_2"

  - local_name_prefix: "prefix_3_backup"
    remote_path: "prefix_3"
